[font]
#[[font]]
# If you want to use the Nerd Font variant
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }

size = 14

[window]
opacity = 0.6

[window.padding]
x = 4
y = 4

[general]
import = [
    "~/.config/alacritty/dracula.toml"
]
